# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_github_packages:
  - r-lib/covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev gfortran
  - R -q -e "install.packages('udunits2',configure.args='--with-udunits2-include=/usr/include/udunits2')"
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
